sudo: required

services:
  - docker

before_install:
  - docker build -t lfteran42/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true lfteran42/docker-react npm run test -- --coverage
